# Generated by Django 2.1.4 on 2018-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryname', models.CharField(db_column='primaryName', max_length=255)),
                ('birthyear', models.CharField(blank=True, db_column='birthYear', max_length=4, null=True)),
                ('deathyear', models.CharField(blank=True, db_column='deathYear', max_length=4, null=True)),
                ('knownfortitles', models.CharField(blank=True, db_column='knownForTitles', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Actor name',
                'verbose_name_plural': 'Actors names',
                'db_table': 'actor',
                'ordering': ['primaryname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActorLookup',
            fields=[
                ('actor_lookup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Actor lookup value',
                'verbose_name_plural': 'Actor lookup values',
                'db_table': 'actor_lookup',
                'ordering': ['a_title', 'actor'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryname', models.CharField(db_column='primaryName', max_length=255)),
                ('birthyear', models.CharField(blank=True, db_column='birthYear', max_length=4, null=True)),
                ('deathyear', models.CharField(blank=True, db_column='deathYear', max_length=4, null=True)),
                ('knownfortitles', models.CharField(blank=True, db_column='knownForTitles', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Director name',
                'verbose_name_plural': 'Directors names',
                'db_table': 'director',
                'ordering': ['primaryname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorLookup',
            fields=[
                ('director_lookup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Director lookup value',
                'verbose_name_plural': 'Director lookup values',
                'db_table': 'director_lookup',
                'ordering': ['d_title', 'director'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titletype', models.CharField(blank=True, db_column='titleType', max_length=100, null=True)),
                ('primarytitle', models.CharField(db_column='primaryTitle', max_length=500)),
                ('originaltitle', models.CharField(blank=True, db_column='originalTitle', max_length=500, null=True)),
                ('isadult', models.IntegerField(blank=True, db_column='isAdult', null=True)),
                ('startyear', models.CharField(blank=True, db_column='startYear', max_length=4, null=True)),
                ('endyear', models.CharField(blank=True, db_column='endYear', max_length=4, null=True)),
                ('runtimeminutes', models.CharField(blank=True, db_column='runtimeMinutes', max_length=10, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('averagerating', models.FloatField(blank=True, db_column='averageRating', null=True)),
                ('numvotes', models.IntegerField(blank=True, db_column='numVotes', null=True)),
            ],
            options={
                'verbose_name': 'Film title',
                'verbose_name_plural': 'Film names',
                'db_table': 'title',
                'ordering': ['-averagerating'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('writer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primaryname', models.CharField(db_column='primaryName', max_length=255)),
                ('birthyear', models.CharField(blank=True, db_column='birthYear', max_length=4, null=True)),
                ('deathyear', models.CharField(blank=True, db_column='deathYear', max_length=4, null=True)),
                ('knownfortitles', models.CharField(blank=True, db_column='knownForTitles', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Writer name',
                'verbose_name_plural': 'Writers names',
                'db_table': 'writer',
                'ordering': ['primaryname'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriterLookup',
            fields=[
                ('writer_lookup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Writer lookup value',
                'verbose_name_plural': 'Writer lookup values',
                'db_table': 'writer_lookup',
                'ordering': ['w_title', 'writer'],
                'managed': False,
            },
        ),
    ]
